server:
  port: 8081

temporal:
  server: localhost:7233 #địa chỉ temporal
  namespace: default #namespace trong temporal

management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus
